# How to test easily if things works
# gh release delete 0.5.6 -y;rm -f TOUCHME;git amend -a --no-edit && git tag --force 0.5.6 && goreleaser release --rm-dist
env:
  - TARGET_BRANCH=FOFOFOOFOFO
  - TARGET_PAC_VERSION={{ .Tag }}

before:
  hooks:
    - /bin/sh -c "echo {{ .Tag }} > TOUCHME"

release:
  footer: |
    **Full Changelog**: https://github.com/goreleaser/goreleaser/compare/{{ .PreviousTag }}...{{ .Tag }}
    ## What to do next?
    - Read the [documentation](https://goreleaser.com/intro/)
    - Check out the [GoReleaser Pro](https://goreleaser.com/pro) distribution
    - Join our [Discord server](https://discord.gg/RGEBtg8vQ6)
    - Follow us on [Twitter](https://twitter.com/goreleaser)
  extra_files:
    - glob: ./TOUCHME
