---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: scratchpad-run-test
spec:
  pipelineRef:
    name: scratchpad-pr
  params:
    - name: repo_url
      value: {{repo_html_url}}
    - name: revision
      value: {{pull_request_head_ref}}
    - name: golangci-flags
      value: "-v --timeout 15m --disable errcheck"
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
