---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scratchpad-pr
spec:
  params:
    - name: repo_url
    - name: revision
  workspaces:
  - name: source
  tasks:
    - name: giggles
      taskSpec:
        params:
          - name: package
          - name: flags
          - name: version
        workspaces:
        - name: source
        steps:
          - name: giggle
            # we get bumped out when usingh the official image with docker.io
            # ratelimit so workaround this.
            image: registry.redhat.io/ubi8/ubi-minimal
            workingdir: $(workspaces.source.path)
            script: |
              echo "just for giggle"
      params:
        - name: package
          value: "."
        - name: flags
          value: "-v --timeout 15m"
        - name: version
          value: 1.35.2
      workspaces:
        - name: source
          workspace: source
