---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scratchpad-pr
spec:
  params:
    - name: repo_url
    - name: revision
  workspaces:
  - name: source
  tasks:
    - name: fetch
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
      workspaces:
      - name: output
        workspace: source
    - name: buildah
      taskRef:
        name: buildah
      runAfter: [lint]
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/testing        
      workspaces:
        - name: source          
          workspace: source
    - name: lint
      runAfter: [fetch]
      taskSpec:
        params:
          - name: package
          - name: flags
          - name: version
        workspaces:
        - name: source
        steps:
          - name: lint
            # we get bumped out when usingh the official image with docker.io
            # ratelimit so workaround this.
            image: registry.access.redhat.com/ubi8/go-toolset:1.14.12
            workingdir: $(workspaces.source.path)
            script: |
              sleep 1000
              version=$(params.version)
              curl -s -L -o- https://github.com/golangci/golangci-lint/releases/download/v${version}/golangci-lint-${version}-linux-amd64.tar.gz|tar xzf -  */golangci-lint --strip-components=1
      params:
        - name: package
          value: "."
        - name: flags
          value: "-v --timeout 15m"
        - name: version
          value: 1.35.2
      workspaces:
        - name: source
          workspace: source
