---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-scratch-my-back
spec:
  tasks:
    - name: task-spec
      taskSpec:
        steps:
          - name: task-spec
            image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
            script: |
              echo "Hello from taskSpec"
              exit 0
