---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-scratch-my-back
spec:
  params:
    - name: repo_url
    - name: revision
  tasks:

    - name: task-spec
      taskSpec:
        steps:
          - name: task-spec
            image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
            script: |
              echo "Hello from taskSpec"
              exit 0

    - name: task-from-tektondir
      taskRef:
        name: task-from-tektondir

    - name: task-from-remote
      taskRef:
        name: task-remote
