---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scratchpad-pr
spec:
  tasks:
    - name: lint
      taskSpec:
        steps:
          - name: exit-0
            image: registry.access.redhat.com/ubi8/ubi-minimal:8.2
            script: "exit 0"
  finally:
    - name: finally
      taskSpec:
        steps:
          - name: send-to-slack
            env:
              - name: SLACK_WEBHOOK_URL
                valueFrom:
                  secretKeyRef:
                    name: chmouel-scratchpad-slack-webhook
                    key: hook_url
              - name: PIPELINERUN
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tekton.dev/pipelineRun']
            image: quay.io/chmouel/tekton-asa-code:latest
            script: |
              python3 /code/misc/send-slack-notifications.py --github-pull-label="{{pull_request.labels}}" --label-to-check=nightly-ci \
              --failure-subject="Scratchpad has failed on {{pull_request.html_url}} :fb-sad: :crying_cat_face: :crying:" \
              --failure-url-icon="https://www.vhv.rs/dpng/d/415-4154815_grumpy-cat-png-photos-grumpy-cat-png-transparent.png" \
              --success-subject="Scratchpad ran succesfully on {{pull_request.html_url}} :pipelinedance: :dancing-penguin: :yay2:" \
              --success-url-icon="https://github.com/tektoncd.png" \
              --log-url="{{openshift_console_pipelinerun_href}}"
